-- Databricks notebook source
-- MAGIC %md
-- MAGIC # COVID-19 global analysis 2020-2024 (OWID) - SQL pipeline (Databricks SQL)
-- MAGIC Generated by `scripts/build_databricks.py` from `sql/`. Executed on a serverless SQL warehouse.
-- MAGIC
-- MAGIC 1. Upload the full raw files to the Unity Catalog volume `/Volumes/workspace/da_learn_14/raw` (see `databricks/SETUP.md`).
-- MAGIC 2. Attach to a SQL warehouse (or DBR 13.3+) and *Run all*.
-- MAGIC 3. Cells: config -> 01 staging (`read_files`) -> 02 cleaning -> 03 star schema -> 04 KPIs -> 05 data quality -> visual queries.

-- COMMAND ----------

-- Config
CREATE SCHEMA IF NOT EXISTS workspace.da_learn_14;
CREATE VOLUME IF NOT EXISTS workspace.da_learn_14.raw;
USE CATALOG workspace;
USE SCHEMA da_learn_14;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 01 Staging (raw landing, no type inference for CSV; casting happens in 02)

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_covid AS
SELECT * EXCEPT (_rescued_data)
FROM read_files('/Volumes/workspace/da_learn_14/raw/owid-covid-data.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 02 Cleaning (`sql/02_cleaning.sql`)

-- COMMAND ----------

-- 02_cleaning.sql  (Spark SQL dialect; DuckDB via 00 shims)

CREATE OR REPLACE TABLE cln_typed AS
SELECT
  trim(iso_code)                                                   AS iso_code,
  NULLIF(trim(continent), '')                                      AS continent,
  trim(location)                                                   AS location,
  to_date(trim(date))                                              AS obs_date,
  TRY_CAST(total_cases AS DOUBLE)                                  AS total_cases,
  TRY_CAST(new_cases AS DOUBLE)                                    AS new_cases,
  TRY_CAST(total_deaths AS DOUBLE)                                 AS total_deaths,
  TRY_CAST(new_deaths AS DOUBLE)                                   AS new_deaths,
  TRY_CAST(total_tests AS DOUBLE)                                  AS total_tests,
  TRY_CAST(total_vaccinations AS DOUBLE)                           AS total_vaccinations,
  TRY_CAST(people_vaccinated AS DOUBLE)                            AS people_vaccinated,
  TRY_CAST(people_fully_vaccinated AS DOUBLE)                      AS people_fully_vaccinated,
  TRY_CAST(total_boosters AS DOUBLE)                               AS total_boosters,
  TRY_CAST(people_vaccinated_per_hundred AS DOUBLE)                AS people_vaccinated_per_hundred,
  TRY_CAST(stringency_index AS DOUBLE)                             AS stringency_index,
  TRY_CAST(excess_mortality_cumulative_per_million AS DOUBLE)      AS excess_mortality_cum_per_million,
  TRY_CAST(population AS DOUBLE)                                   AS population,
  TRY_CAST(gdp_per_capita AS DOUBLE)                               AS gdp_per_capita,
  TRY_CAST(median_age AS DOUBLE)                                   AS median_age,
  TRY_CAST(aged_65_older AS DOUBLE)                                AS aged_65_older,
  TRY_CAST(life_expectancy AS DOUBLE)                              AS life_expectancy,
  TRY_CAST(hospital_beds_per_thousand AS DOUBLE)                   AS hospital_beds_per_thousand,
  CASE WHEN trim(iso_code) IN ('OWID_ENG', 'OWID_SCT', 'OWID_WLS', 'OWID_NIR') THEN 'subnational'
       WHEN NULLIF(trim(continent), '') IS NOT NULL THEN 'country'
       ELSE 'aggregate' END                                        AS entity_type
FROM stg_covid
WHERE to_date(trim(date)) IS NOT NULL AND NULLIF(trim(iso_code), '') IS NOT NULL;

-- COMMAND ----------

-- Some (iso_code, date) pairs appear twice: one row carries cases/deaths, the other vaccinations.

CREATE OR REPLACE TABLE cln_merged AS
SELECT iso_code, obs_date, entity_type,
  MAX(continent) AS continent, MAX(location) AS location, COUNT(*) AS source_rows,
  MAX(total_cases) AS total_cases, MAX(new_cases) AS new_cases, MAX(total_deaths) AS total_deaths,
  MAX(new_deaths) AS new_deaths, MAX(total_tests) AS total_tests, MAX(total_vaccinations) AS total_vaccinations,
  MAX(people_vaccinated) AS people_vaccinated, MAX(people_fully_vaccinated) AS people_fully_vaccinated,
  MAX(total_boosters) AS total_boosters, MAX(people_vaccinated_per_hundred) AS people_vaccinated_per_hundred,
  MAX(stringency_index) AS stringency_index, MAX(excess_mortality_cum_per_million) AS excess_mortality_cum_per_million,
  MAX(population) AS population, MAX(gdp_per_capita) AS gdp_per_capita, MAX(median_age) AS median_age,
  MAX(aged_65_older) AS aged_65_older, MAX(life_expectancy) AS life_expectancy,
  MAX(hospital_beds_per_thousand) AS hospital_beds_per_thousand
FROM cln_typed
GROUP BY iso_code, obs_date, entity_type;

-- COMMAND ----------

-- Country-day table with quality flags.

CREATE OR REPLACE TABLE cln_country_daily AS
SELECT m.*,
  CASE WHEN m.total_cases < LAG(m.total_cases) OVER (PARTITION BY m.iso_code ORDER BY m.obs_date) THEN 1 ELSE 0 END AS dq_cases_revised_down,
  CASE WHEN m.people_vaccinated > m.population THEN 1 ELSE 0 END                                              AS dq_vax_over_population,
  CASE WHEN COALESCE(m.new_cases, 0) < 0 OR COALESCE(m.new_deaths, 0) < 0 THEN 1 ELSE 0 END                  AS dq_negative_new
FROM cln_merged m
WHERE m.entity_type = 'country';

-- COMMAND ----------

-- OWID aggregates (World, continents, income groups, EU) kept for reconciliation and equity analysis.

CREATE OR REPLACE TABLE cln_aggregate_daily AS
SELECT * FROM cln_merged WHERE entity_type = 'aggregate';

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 03 Star schema (`sql/03_model.sql`)

-- COMMAND ----------

-- 03_model.sql  Star schema: fact_covid_daily (country x day), fact_country_month (country x month),

CREATE OR REPLACE TABLE dim_country AS
SELECT ROW_NUMBER() OVER (ORDER BY iso_code) AS country_key, iso_code, location, continent,
       CAST(population AS BIGINT) AS population, gdp_per_capita, median_age, aged_65_older, life_expectancy,
       hospital_beds_per_thousand,
       CASE WHEN population >= 1000000 THEN 1 ELSE 0 END AS pop_1m_plus_flag
FROM (SELECT iso_code, MAX(location) AS location, MAX(continent) AS continent, MAX(population) AS population,
             MAX(gdp_per_capita) AS gdp_per_capita, MAX(median_age) AS median_age, MAX(aged_65_older) AS aged_65_older,
             MAX(life_expectancy) AS life_expectancy, MAX(hospital_beds_per_thousand) AS hospital_beds_per_thousand
      FROM cln_country_daily GROUP BY iso_code) c;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_date AS
SELECT DISTINCT
  CAST(year(obs_date) * 10000 + month(obs_date) * 100 + day(obs_date) AS INT) AS date_key,
  obs_date AS full_date, year(obs_date) AS year, quarter(obs_date) AS quarter, month(obs_date) AS month,
  CAST(year(obs_date) * 100 + month(obs_date) AS INT) AS year_month,
  concat(CAST(year(obs_date) AS STRING), '-', lpad(CAST(month(obs_date) AS STRING), 2, '0')) AS year_month_label,
  dayofweek(obs_date) AS day_of_week
FROM cln_merged;

-- COMMAND ----------

CREATE OR REPLACE TABLE fact_covid_daily AS
SELECT
  CAST(year(d.obs_date) * 10000 + month(d.obs_date) * 100 + day(d.obs_date) AS INT) AS date_key,
  c.country_key, d.obs_date,
  CAST(d.new_cases AS BIGINT) AS new_cases, CAST(d.new_deaths AS BIGINT) AS new_deaths,
  CAST(d.total_cases AS BIGINT) AS total_cases, CAST(d.total_deaths AS BIGINT) AS total_deaths,
  CAST(d.people_vaccinated AS BIGINT) AS people_vaccinated,
  CAST(d.people_fully_vaccinated AS BIGINT) AS people_fully_vaccinated,
  CAST(d.total_boosters AS BIGINT) AS total_boosters,
  CAST(d.total_vaccinations AS BIGINT) AS total_vaccinations,
  d.stringency_index, d.excess_mortality_cum_per_million,
  d.dq_cases_revised_down, d.dq_vax_over_population, d.source_rows
FROM cln_country_daily d
JOIN dim_country c ON c.iso_code = d.iso_code;

-- COMMAND ----------

-- Monthly grain: flows are summed, stocks (cumulative counts) take the month-end (max) value.

CREATE OR REPLACE TABLE fact_country_month AS
SELECT f.country_key, CAST(year(f.obs_date) * 100 + month(f.obs_date) AS INT) AS year_month,
  SUM(COALESCE(f.new_cases, 0)) AS new_cases, SUM(COALESCE(f.new_deaths, 0)) AS new_deaths,
  MAX(f.total_cases) AS total_cases_eom, MAX(f.total_deaths) AS total_deaths_eom,
  MAX(f.people_vaccinated) AS people_vaccinated_eom, MAX(f.people_fully_vaccinated) AS people_fully_vaccinated_eom,
  MAX(f.total_boosters) AS total_boosters_eom, ROUND(AVG(f.stringency_index), 2) AS avg_stringency
FROM fact_covid_daily f
GROUP BY f.country_key, CAST(year(f.obs_date) * 100 + month(f.obs_date) AS INT);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 04 Business KPIs (`sql/04_analysis.sql`)

-- COMMAND ----------

-- 04_analysis.sql  KPIs and business questions (countries only; aggregates used for equity + reconciliation)

CREATE OR REPLACE TABLE a_country_latest AS
WITH t AS (
  SELECT country_key, MAX(total_cases) AS total_cases, MAX(total_deaths) AS total_deaths,
         MAX(people_vaccinated) AS people_vaccinated, MAX(people_fully_vaccinated) AS people_fully_vaccinated,
         MAX(total_boosters) AS total_boosters, MAX(obs_date) AS last_date
  FROM fact_covid_daily GROUP BY country_key
), x AS (
  SELECT country_key, excess_mortality_cum_per_million FROM fact_covid_daily
  WHERE excess_mortality_cum_per_million IS NOT NULL
  QUALIFY ROW_NUMBER() OVER (PARTITION BY country_key ORDER BY obs_date DESC) = 1
)
SELECT c.country_key, c.iso_code, c.location, c.continent, c.population, c.pop_1m_plus_flag, c.median_age, c.gdp_per_capita,
  t.total_cases, t.total_deaths, t.people_vaccinated, t.last_date,
  ROUND(t.total_cases * 1e6 / NULLIF(c.population, 0), 1)             AS cases_per_million,
  ROUND(t.total_deaths * 1e6 / NULLIF(c.population, 0), 1)            AS deaths_per_million,
  ROUND(100.0 * t.total_deaths / NULLIF(t.total_cases, 0), 3)          AS cfr_pct,
  ROUND(100.0 * t.people_vaccinated / NULLIF(c.population, 0), 2)      AS pct_vaccinated,
  ROUND(100.0 * t.people_fully_vaccinated / NULLIF(c.population, 0), 2) AS pct_fully_vaccinated,
  ROUND(100.0 * t.total_boosters / NULLIF(c.population, 0), 2)         AS boosters_per_hundred,
  ROUND(x.excess_mortality_cum_per_million, 1)                         AS excess_mortality_cum_per_million
FROM dim_country c
JOIN t ON t.country_key = c.country_key
LEFT JOIN x ON x.country_key = c.country_key;

-- COMMAND ----------

-- Q2: continent comparison (vaccination share uses only countries that report vaccinations)

CREATE OR REPLACE TABLE a_continent_summary AS
SELECT continent, COUNT(*) AS countries, SUM(population) AS population,
  SUM(total_cases) AS total_cases, SUM(total_deaths) AS total_deaths,
  ROUND(SUM(total_cases) * 1e6 / SUM(population), 1)  AS cases_per_million,
  ROUND(SUM(total_deaths) * 1e6 / SUM(population), 1) AS deaths_per_million,
  ROUND(100.0 * SUM(total_deaths) / NULLIF(SUM(total_cases), 0), 3) AS cfr_pct,
  ROUND(100.0 * SUM(people_vaccinated) / NULLIF(SUM(CASE WHEN people_vaccinated IS NOT NULL THEN population END), 0), 2) AS pct_vaccinated
FROM a_country_latest GROUP BY continent;

-- COMMAND ----------

-- Q3: global timeline

CREATE OR REPLACE TABLE a_monthly_global AS
SELECT m.year_month, concat(substr(CAST(m.year_month AS STRING), 1, 4), '-', substr(CAST(m.year_month AS STRING), 5, 2)) AS month_label,
  SUM(m.new_cases) AS new_cases, SUM(m.new_deaths) AS new_deaths,
  ROUND(100.0 * SUM(m.new_deaths) / NULLIF(SUM(m.new_cases), 0), 3) AS monthly_cfr_pct
FROM fact_country_month m GROUP BY m.year_month;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_yearly AS
SELECT CAST(year_month / 100 AS INT) AS year, SUM(new_cases) AS new_cases, SUM(new_deaths) AS new_deaths,
  ROUND(100.0 * SUM(new_deaths) / NULLIF(SUM(new_cases), 0), 3) AS cfr_pct,
  ROUND(100.0 * SUM(new_deaths) / SUM(SUM(new_deaths)) OVER (), 2) AS pct_of_all_deaths
FROM fact_country_month GROUP BY CAST(year_month / 100 AS INT);

-- COMMAND ----------

CREATE OR REPLACE TABLE a_continent_month AS
SELECT c.continent, m.year_month, SUM(m.new_cases) AS new_cases, SUM(m.new_deaths) AS new_deaths,
  ROUND(SUM(m.new_deaths) * 1e6 / SUM(c.population), 2) AS deaths_per_million
FROM fact_country_month m JOIN dim_country c ON c.country_key = m.country_key
GROUP BY c.continent, m.year_month;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_continent_peak AS
SELECT continent, year_month AS peak_death_month, new_deaths AS peak_month_deaths, deaths_per_million AS peak_deaths_per_million
FROM a_continent_month
QUALIFY ROW_NUMBER() OVER (PARTITION BY continent ORDER BY new_deaths DESC) = 1;

-- COMMAND ----------

-- Q5: vaccination coverage at end-2021 vs deaths per million afterwards (countries >= 1M people)

CREATE OR REPLACE TABLE a_vax_band_outcomes AS
WITH e21 AS (
  SELECT country_key, MAX(people_vaccinated) AS vax_2021, MAX(total_deaths) AS deaths_2021
  FROM fact_covid_daily WHERE obs_date <= DATE'2021-12-31' GROUP BY country_key
), b AS (
  SELECT l.country_key, l.population, l.median_age, l.total_deaths, COALESCE(e.deaths_2021, 0) AS deaths_2021,
    100.0 * e.vax_2021 / l.population AS pct_vax_2021
  FROM a_country_latest l JOIN e21 e ON e.country_key = l.country_key
  WHERE l.pop_1m_plus_flag = 1 AND e.vax_2021 IS NOT NULL AND l.total_deaths IS NOT NULL
)
SELECT CASE WHEN pct_vax_2021 < 40 THEN '1 <40%' WHEN pct_vax_2021 < 60 THEN '2 40-60%'
            WHEN pct_vax_2021 < 75 THEN '3 60-75%' ELSE '4 >=75%' END AS vax_band_end_2021,
  COUNT(*) AS countries,
  ROUND(SUM(deaths_2021) * 1e6 / SUM(population), 1) AS deaths_pm_2020_21,
  ROUND(SUM(total_deaths - deaths_2021) * 1e6 / SUM(population), 1) AS deaths_pm_2022_24,
  ROUND(AVG(median_age), 1) AS avg_median_age
FROM b GROUP BY 1;

-- COMMAND ----------

-- Q6: demographics - deaths per million by median-age band (countries >= 1M people)

CREATE OR REPLACE TABLE a_age_band_deaths AS
SELECT CASE WHEN median_age < 25 THEN '1 <25' WHEN median_age < 35 THEN '2 25-35'
            WHEN median_age < 42 THEN '3 35-42' ELSE '4 42+' END AS median_age_band,
  COUNT(*) AS countries, ROUND(SUM(total_deaths) * 1e6 / SUM(population), 1) AS deaths_per_million,
  ROUND(100.0 * SUM(total_deaths) / NULLIF(SUM(total_cases), 0), 3) AS cfr_pct
FROM a_country_latest WHERE pop_1m_plus_flag = 1 AND median_age IS NOT NULL AND total_deaths IS NOT NULL
GROUP BY 1;

-- COMMAND ----------

-- Q7: vaccine equity by World Bank income group (OWID aggregates, latest reported value)

CREATE OR REPLACE TABLE a_income_vaccination AS
SELECT location AS income_group, obs_date AS as_of, people_vaccinated_per_hundred AS pct_vaccinated
FROM cln_aggregate_daily
WHERE iso_code IN ('OWID_HIC', 'OWID_UMC', 'OWID_LMC', 'OWID_LIC', 'OWID_WRL') AND people_vaccinated_per_hundred IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY location ORDER BY obs_date DESC) = 1;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_kpi_headline AS
WITH s AS (SELECT COUNT(*) AS countries, SUM(population) AS population, SUM(total_cases) AS total_cases,
                  SUM(total_deaths) AS total_deaths FROM a_country_latest),
     d AS (SELECT MIN(obs_date) AS first_date, MAX(obs_date) AS last_date, COUNT(*) AS country_days FROM fact_covid_daily),
     p AS (SELECT month_label AS peak_death_month, new_deaths AS peak_month_deaths FROM a_monthly_global
           ORDER BY new_deaths DESC LIMIT 1),
     w AS (SELECT pct_vaccinated AS world_pct_vaccinated FROM a_income_vaccination WHERE income_group = 'World')
SELECT s.countries, d.country_days, d.first_date, d.last_date, CAST(s.population AS BIGINT) AS population,
  CAST(s.total_cases AS BIGINT) AS total_cases, CAST(s.total_deaths AS BIGINT) AS total_deaths,
  ROUND(100.0 * s.total_deaths / s.total_cases, 3) AS cfr_pct,
  ROUND(s.total_deaths * 1e6 / s.population, 1) AS deaths_per_million,
  w.world_pct_vaccinated, p.peak_death_month, CAST(p.peak_month_deaths AS BIGINT) AS peak_month_deaths
FROM s CROSS JOIN d CROSS JOIN p CROSS JOIN w;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 05 Data-quality checks (`sql/05_quality_checks.sql`)

-- COMMAND ----------

-- 05_quality_checks.sql  before/after counts, DQ issue counts and hard assertions

CREATE OR REPLACE TABLE dq_row_counts AS
SELECT 'raw rows' AS entity, (SELECT COUNT(*) FROM stg_covid) AS raw_rows,
       (SELECT COUNT(*) FROM (SELECT DISTINCT iso_code, date FROM stg_covid) x) AS distinct_keys,
       (SELECT COUNT(*) FROM cln_merged) AS clean_rows, 'iso_code + date' AS grain
UNION ALL SELECT 'country-days', NULL, NULL, (SELECT COUNT(*) FROM cln_country_daily), 'country + date'
UNION ALL SELECT 'aggregate-days', NULL, NULL, (SELECT COUNT(*) FROM cln_aggregate_daily), 'OWID aggregate + date'
UNION ALL SELECT 'fact_covid_daily', NULL, NULL, (SELECT COUNT(*) FROM fact_covid_daily), 'country + day'
UNION ALL SELECT 'fact_country_month', NULL, NULL, (SELECT COUNT(*) FROM fact_country_month), 'country + month'
UNION ALL SELECT 'dim_country', NULL, NULL, (SELECT COUNT(*) FROM dim_country), 'country'
UNION ALL SELECT 'dim_date', NULL, NULL, (SELECT COUNT(*) FROM dim_date), 'day';

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_issues AS
SELECT 'raw: split duplicate rows merged (iso_code, date)' AS check_name,
       (SELECT COUNT(*) FROM stg_covid) - (SELECT COUNT(*) FROM cln_merged) AS affected_rows
UNION ALL SELECT 'raw: OWID aggregate rows (World, continents, income groups, EU)', (SELECT COUNT(*) FROM cln_typed WHERE entity_type = 'aggregate')
UNION ALL SELECT 'raw: UK sub-national rows dropped (double count)', (SELECT COUNT(*) FROM cln_typed WHERE entity_type = 'subnational')
UNION ALL SELECT 'country-days: new_cases NULL', (SELECT COUNT(*) FROM cln_country_daily WHERE new_cases IS NULL)
UNION ALL SELECT 'country-days: new_cases = 0 (weekly reporting gaps)', (SELECT COUNT(*) FROM cln_country_daily WHERE new_cases = 0)
UNION ALL SELECT 'country-days: cumulative cases revised down', (SELECT SUM(dq_cases_revised_down) FROM cln_country_daily)
UNION ALL SELECT 'country-days: people_vaccinated > population', (SELECT SUM(dq_vax_over_population) FROM cln_country_daily)
UNION ALL SELECT 'countries: vaccinated share > 100% (stale population or non-residents)', (SELECT COUNT(*) FROM a_country_latest WHERE pct_vaccinated > 100)
UNION ALL SELECT 'countries: never reported a vaccination', (SELECT COUNT(*) FROM a_country_latest WHERE people_vaccinated IS NULL)
UNION ALL SELECT 'country-days: negative new cases/deaths', (SELECT SUM(dq_negative_new) FROM cln_country_daily);

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_assertions AS
WITH w AS (SELECT MAX(total_cases) AS wc, MAX(total_deaths) AS wd FROM cln_aggregate_daily WHERE iso_code = 'OWID_WRL'),
c AS (
  SELECT 'one row per country-day' AS check_name,
         (SELECT COUNT(*) FROM (SELECT country_key, date_key FROM fact_covid_daily GROUP BY 1, 2 HAVING COUNT(*) > 1) x) AS failed_rows
  UNION ALL SELECT 'every fact row has a country', (SELECT COUNT(*) FROM fact_covid_daily f LEFT JOIN dim_country d ON d.country_key = f.country_key WHERE d.country_key IS NULL)
  UNION ALL SELECT 'every fact row has a date', (SELECT COUNT(*) FROM fact_covid_daily f LEFT JOIN dim_date d ON d.date_key = f.date_key WHERE d.date_key IS NULL)
  UNION ALL SELECT 'every country has continent + population', (SELECT COUNT(*) FROM dim_country WHERE continent IS NULL OR population IS NULL)
  UNION ALL SELECT 'no negative new cases or deaths', (SELECT COUNT(*) FROM fact_covid_daily WHERE new_cases < 0 OR new_deaths < 0)
  UNION ALL SELECT 'deaths never exceed cases (country final)', (SELECT COUNT(*) FROM a_country_latest WHERE total_deaths > total_cases)
  UNION ALL SELECT 'monthly new_cases sum = daily sum', (SELECT CASE WHEN (SELECT SUM(new_cases) FROM fact_country_month) = (SELECT SUM(COALESCE(new_cases, 0)) FROM fact_covid_daily) THEN 0 ELSE 1 END)
  UNION ALL SELECT 'country cases within 1% of OWID World', (SELECT CASE WHEN ABS(k.total_cases - w.wc) / w.wc <= 0.01 THEN 0 ELSE 1 END FROM a_kpi_headline k CROSS JOIN w)
  UNION ALL SELECT 'country deaths within 1% of OWID World', (SELECT CASE WHEN ABS(k.total_deaths - w.wd) / w.wd <= 0.01 THEN 0 ELSE 1 END FROM a_kpi_headline k CROSS JOIN w)
  UNION ALL SELECT 'UK sub-national rows excluded', (SELECT COUNT(*) FROM dim_country WHERE iso_code IN ('OWID_ENG', 'OWID_SCT', 'OWID_WLS', 'OWID_NIR'))
)
SELECT check_name, failed_rows, CASE WHEN failed_rows = 0 THEN 'PASS' ELSE 'FAIL' END AS status FROM c;

-- COMMAND ----------

SELECT * FROM dq_row_counts ORDER BY entity;

-- COMMAND ----------

SELECT * FROM dq_assertions ORDER BY status, check_name;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Visual queries (same as the Lakeview dashboard)

-- COMMAND ----------

SELECT * FROM a_kpi_headline;

-- COMMAND ----------

-- Visualization: Global reported deaths per month (line: x=month_label, y=new_deaths)
SELECT month_label, new_deaths FROM a_monthly_global ORDER BY year_month;

-- COMMAND ----------

-- Visualization: Deaths per million by continent (hbar: x=continent, y=deaths_per_million)
SELECT continent, deaths_per_million FROM a_continent_summary ORDER BY deaths_per_million DESC;

-- COMMAND ----------

-- Visualization: Highest deaths per million (pop >= 1M) (hbar: x=location, y=deaths_per_million)
SELECT location, deaths_per_million FROM a_country_latest WHERE pop_1m_plus_flag = 1 ORDER BY deaths_per_million DESC LIMIT 10;

-- COMMAND ----------

-- Visualization: Case fatality rate by year (%) (bar: x=year, y=cfr_pct)
SELECT CAST(year AS STRING) AS year, cfr_pct FROM a_yearly ORDER BY year;

-- COMMAND ----------

-- Visualization: Share with >= 1 vaccine dose by income group (hbar: x=income_group, y=pct_vaccinated)
SELECT replace(income_group, '-income countries', ' income') AS income_group, pct_vaccinated FROM a_income_vaccination ORDER BY pct_vaccinated DESC;

-- COMMAND ----------

-- Visualization: Deaths per million by median-age band (bar: x=median_age_band, y=deaths_per_million)
SELECT median_age_band, deaths_per_million FROM a_age_band_deaths ORDER BY median_age_band;
